/**
 * @(#)P2.java
 *
 * P2 application
 *
 * @author 
 * @version 1.00 2015/3/12
 */

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */ 
public class P2 {
    public static void main(String[] args) {
    	long sum1=0;
    	long sum2=1;
    	long sum3=0;
    	long evensum=0;
    	while(sum3<4000000){
    		sum3=sum1+sum2;
    		sum1=sum2;
    		sum2=sum3;
    		if(sum3%2==0){
    			evensum=evensum+sum3;
    		}
    	}
    	System.out.println(evensum);
    }
}
